[package]
name = "guix"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
octocrab = { git = "https://github.com/XAMPPRocky/octocrab", branch = "main" }
tokio = { version = "1", features = ["full"] }
util = { path = "../util" ,features=["github"]}
